# Generated by Django 3.0.2 on 2020-01-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='petstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('vaccination_records', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
